package com.muse.classroom.assignment.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

import java.util.List;
import java.util.Map;

@Service
public class GeminiService {

    private final WebClient webClient;
    private final String geminiApiKey;
    private final String geminiGenerateUrl;
    private final ObjectMapper objectMapper;

    public GeminiService(
            @Value("${gemini.api.key}") String geminiApiKey,
            @Value("${gemini.api.url}") String geminiGenerateUrl,
            ObjectMapper objectMapper) {
        this.webClient = WebClient.builder().build();
        this.geminiApiKey = geminiApiKey;
        this.geminiGenerateUrl = geminiGenerateUrl;
        this.objectMapper = objectMapper;
    }

    public Mono<GradingResult> gradeSubmission(String assignmentTitle, String description, String criteria,
            String studentSubmission, int maxScore) {
        String prompt = String.format(
                "You are an expert academic grader. Grade the following student submission based on the provided assignment details and criteria.\n\n"
                        +
                        "Assignment Title: %s\n" +
                        "Description: %s\n" +
                        "Grading Criteria/Rubric: %s\n" +
                        "Max Score: %d\n\n" +
                        "Student Submission:\n%s\n\n" +
                        "Provide the output in the following JSON format ONLY (no markdown, no code blocks):\n" +
                        "{\n" +
                        "  \"score\": <integer_score>,\n" +
                        "  \"feedback\": \"<detailed_feedback>\"\n" +
                        "}",
                assignmentTitle, description, criteria, maxScore, studentSubmission);

        return generateContent(prompt)
                .map(response -> {
                    try {
                        // Clean up response if it contains markdown code blocks
                        String jsonResponse = response.replace("```json", "").replace("```", "").trim();
                        JsonNode root = objectMapper.readTree(jsonResponse);
                        int score = root.path("score").asInt();
                        String feedback = root.path("feedback").asText();
                        return new GradingResult(score, feedback);
                    } catch (Exception e) {
                        throw new RuntimeException("Failed to parse AI grading response", e);
                    }
                });
    }

    private Mono<String> generateContent(String prompt) {
        Map<String, Object> content = Map.of("parts", List.of(Map.of("text", prompt)));
        Map<String, Object> req = Map.of("contents", List.of(content));

        return webClient.post()
                .uri(geminiGenerateUrl + "?key=" + geminiApiKey)
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(req)
                .retrieve()
                .onStatus(status -> status.isError(), response -> {
                    return response.bodyToMono(String.class)
                            .flatMap(errorBody -> {
                                System.err.println("Gemini API Error: " + response.statusCode() + " - " + errorBody);
                                return Mono.error(new RuntimeException(
                                        "Gemini API Error: " + response.statusCode() + " - " + errorBody));
                            });
                })
                .bodyToMono(JsonNode.class)
                .map(response -> {
                    JsonNode candidates = response.path("candidates");
                    if (candidates.isArray() && candidates.size() > 0) {
                        JsonNode parts = candidates.get(0).path("content").path("parts");
                        if (parts.isArray() && parts.size() > 0) {
                            return parts.get(0).path("text").asText();
                        }
                    }
                    throw new RuntimeException("No content generated by AI");
                });
    }

    public static class GradingResult {
        public int score;
        public String feedback;

        public GradingResult(int score, String feedback) {
            this.score = score;
            this.feedback = feedback;
        }
    }
}
