-- V1__create_notes_table.sql
CREATE TABLE notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(512) NOT NULL,
  content TEXT,
  author_id BIGINT,
  author_name VARCHAR(255),
  excerpt VARCHAR(1024),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_notes_title ON notes(title);
CREATE INDEX idx_notes_updated_at ON notes(updated_at);