ALTER TABLE users ADD COLUMN bio VARCHAR(150);
ALTER TABLE users ADD COLUMN website VARCHAR(200);
ALTER TABLE users ADD COLUMN phone_number VARCHAR(20);
ALTER TABLE users ADD COLUMN avatar_url VARCHAR(255);
